FROM --platform=amd64 ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
		ca-certificates wget vim cmake ninja-build protobuf-compiler \
		libprotobuf-dev build-essential cmake curl ca-certificates screen \
  	&& rm -rf /var/lib/apt/lists/*

WORKDIR /opt

RUN curl -o ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && chmod +x ~/miniconda.sh \
    && ~/miniconda.sh -b -p /opt/conda \
    && rm ~/miniconda.sh \
    && /opt/conda/bin/conda install -y python=3.8 \
    && /opt/conda/bin/conda install -y numpy matplotlib tqdm \
    && /opt/conda/bin/conda install -y -c conda-forge multiprocess easydict \
    && /opt/conda/bin/conda clean -ya

ENV PATH /opt/conda/bin:$PATH

ENV PYTHONPATH "${PYTHONPATH}:/host"
